name: ui
description: Ribbit web UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auth0_flutter: ^1.2.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  logger: ^1.4.0
  go_router: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
