name: ui
description: Ribbit web UI
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logger: ^1.4.0
  go_router: ^9.0.3
  jiffy: ^6.2.1
  flutter_web_auth: ^0.5.0
  shared_preferences: ^2.2.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
