Transform: AWS::Serverless-2016-10-31

Parameters:
  CorsOrigins:
    Type: CommaDelimitedList
  JwtAudience:
    Type: String

Globals:
  Function:
    Runtime: java17
    MemorySize: 2048
    Environment:
      Variables:
        CORS_ORIGINS: !Join [ ',', !Ref CorsOrigins ]
#        jwt_audience: !Ref JwtAudience
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: [ Authorization ]
        AllowMethods: [ GET, POST, PUT, DELETE ]
        AllowOrigins: !Ref CorsOrigins
        ExposeHeaders: [ '*' ]
      DisableExecuteApiEndpoint: true

  ApiHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Timeout: 10
      Handler: com.ribbit.Http4kLambdaHandler
      Architectures: [arm64]
#      Policies:
#        - DynamoDBCrudPolicy:
#            TableName: !Ref Recipes
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

#  Recipes:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      BillingMode: PAY_PER_REQUEST
#      AttributeDefinitions:
#        - AttributeName: userId
#          AttributeType: S
#        - AttributeName: recipeId
#          AttributeType: S
#      KeySchema:
#        - AttributeName: userId
#          KeyType: HASH
#        - AttributeName: recipeId
#          KeyType: RANGE
