Transform: AWS::Serverless-2016-10-31

Parameters:
  CorsOrigins:
    Type: CommaDelimitedList
  JwtAudiences:
    Type: CommaDelimitedList
  JwtIssuer:
    Type: String

Globals:
  Function:
    Runtime: java17
    MemorySize: 2048
    Environment:
      Variables:
        CORS_ORIGINS: !Join [ ',', !Ref CorsOrigins ]
        JWT_AUDIENCES: !Join [ ',', !Ref JwtAudiences ]
        JWT_ISSUER: !Ref JwtIssuer
        USERS_TABLE_NAME: !Ref Users
        SUBS_TABLE_NAME: !Ref Subs
        POSTS_TABLE_NAME: !Ref Posts
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: [ Authorization ]
        AllowMethods: [ GET, POST, PUT, DELETE ]
        AllowOrigins: !Ref CorsOrigins
        ExposeHeaders: [ '*' ]
      DisableExecuteApiEndpoint: true

  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: com.ribbit.Http4kLambdaHandler
      Architectures: [arm64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Users
        - DynamoDBCrudPolicy:
            TableName: !Ref Subs
        - DynamoDBCrudPolicy:
            TableName: !Ref Posts
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: emailHash
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: emailHash
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: names
          KeySchema:
            - AttributeName: name
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  Subs:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  Posts:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: subId
          AttributeType: S
        - AttributeName: authorId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: sub
          KeySchema:
            - AttributeName: subId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: author
          KeySchema:
            - AttributeName: authorId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL